// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reignite.Infrastructure.Data;

#nullable disable

namespace Reignite.Infrastructure.Migrations
{
    [DbContext(typeof(ReigniteDbContext))]
    [Migration("20260205185358_SimplifiedSeedData")]
    partial class SimplifiedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reignite.Core.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DOBRODOSLI10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountType = "Percentage",
                            DiscountValue = 10.00m,
                            ExpiryDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxUses = 500,
                            MinimumOrderAmount = 50.00m,
                            TimesUsed = 47
                        },
                        new
                        {
                            Id = 2,
                            Code = "LJETO2026",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountType = "Percentage",
                            DiscountValue = 15.00m,
                            ExpiryDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxUses = 200,
                            MinimumOrderAmount = 100.00m,
                            TimesUsed = 23
                        },
                        new
                        {
                            Id = 3,
                            Code = "BESPLATNADOSTAVA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountType = "Fixed",
                            DiscountValue = 7.00m,
                            ExpiryDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxUses = 1000,
                            MinimumOrderAmount = 50.00m,
                            TimesUsed = 156
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Jednostavno dodajte željene proizvode u korpu, unesite podatke za dostavu i izvršite plaćanje. Narudžbu možete pratiti u sekciji 'Moje narudžbe'.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Question = "Kako mogu naručiti proizvode?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Dostava na području Bosne i Hercegovine traje 2-5 radnih dana. Za veće narudžbe ili udaljenije lokacije, rok može biti do 7 radnih dana.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Question = "Koliko traje dostava?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Dostava je besplatna za sve narudžbe iznad 100 KM. Za narudžbe ispod tog iznosa, cijena dostave je 7 KM.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Question = "Da li je dostava besplatna?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Da, imate pravo na povrat proizvoda u roku od 14 dana od prijema. Proizvod mora biti nekorišten i u originalnom pakovanju.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Question = "Mogu li vratiti proizvod?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Prihvatamo plaćanje karticama (Visa, Mastercard), pouzeće i bankovni transfer. Sva online plaćanja su zaštićena SSL enkripcijom.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Question = "Koji su načini plaćanja?"
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Umjetnost izrade predmeta od drveta, od namještaja do dekorativnih komada.",
                            IconUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=100",
                            IsDeleted = false,
                            Name = "Stolarija"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izrada novčanika, remena, torbi i drugih predmeta od kože.",
                            IconUrl = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=100",
                            IsDeleted = false,
                            Name = "Obrada kože"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oblikovanje i kovanje metala u alate i funkcionalne predmete.",
                            IconUrl = "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=100",
                            IsDeleted = false,
                            Name = "Obrada metala"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oblikovanje gline u keramičke predmete, od posuda do skulptura.",
                            IconUrl = "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=100",
                            IsDeleted = false,
                            Name = "Keramika"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Izrada jedinstvenih svijeća sa posebnim mirisima i dizajnom.",
                            IconUrl = "https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=100",
                            IsDeleted = false,
                            Name = "Izrada svijeća"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Umjetnost oblikovanja drveta ručnim alatima.",
                            IconUrl = "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=100",
                            IsDeleted = false,
                            Name = "Rezbarenje"
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalAmount = 123.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalAmount = 188.49m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalAmount = 84.80m,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 78.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 38.50m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 149.99m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 3,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 19.90m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 3,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 45.00m
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesionalni kovački čekić od kaljenog čelika, ergonomska drška od jasena.",
                            IsDeleted = false,
                            Name = "Čekić kovački 500g",
                            Price = 45.00m,
                            ProductCategoryId = 1,
                            ProductImageUrl = "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=400",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Komplet od 12 preciznih šrafcigera sa magnetnim vrhovima.",
                            IsDeleted = false,
                            Name = "Set šrafcigera 12 kom",
                            Price = 32.50m,
                            ProductCategoryId = 1,
                            ProductImageUrl = "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=400",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Profesionalno dlijeto za drvo širine 25mm, oštrica od krom-vanadijskog čelika.",
                            IsDeleted = false,
                            Name = "Dlijeto ručno 25mm",
                            Price = 38.50m,
                            ProductCategoryId = 1,
                            ProductImageUrl = "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tradicionalna japanska pila za precizne rezove. Tanka oštrica za fine radove.",
                            IsDeleted = false,
                            Name = "Ručna pila japanska",
                            Price = 67.90m,
                            ProductCategoryId = 1,
                            ProductImageUrl = "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Visokokvalitetna hrastova daska, dimenzije 200x30x3cm, sušena u komori.",
                            IsDeleted = false,
                            Name = "Hrastova daska premium",
                            Price = 78.00m,
                            ProductCategoryId = 2,
                            ProductImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prirodni orahov furnir debljine 0.6mm, idealan za završnu obradu namještaja.",
                            IsDeleted = false,
                            Name = "Orahov furnir 1m²",
                            Price = 55.90m,
                            ProductCategoryId = 2,
                            ProductImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Visokokvalitetna goveđa koža debljine 1.5mm. Prirodna smeđa boja.",
                            IsDeleted = false,
                            Name = "Goveđa koža premium 1m²",
                            Price = 85.00m,
                            ProductCategoryId = 2,
                            ProductImageUrl = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kvalitetni bukov blok dimenzija 15x15x30cm. Sušeno drvo bez čvorova.",
                            IsDeleted = false,
                            Name = "Bukov blok za rezbarenje",
                            Price = 35.00m,
                            ProductCategoryId = 2,
                            ProductImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sve za početak stolarije: ručna pila, čekić, 3 dlijeta, metar, kutnik i vodič.",
                            IsDeleted = false,
                            Name = "Stolarski komplet za početnike",
                            Price = 149.99m,
                            ProductCategoryId = 3,
                            ProductImageUrl = "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set za obradu kože: 2 noža, šila, igle, voskirani konac, probijač i kalup.",
                            IsDeleted = false,
                            Name = "Komplet za obradu kože",
                            Price = 189.00m,
                            ProductCategoryId = 3,
                            ProductImageUrl = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Osnovni set za rezbarenje: 4 noža, brusilica, 2 lipova bloka i priručnik.",
                            IsDeleted = false,
                            Name = "Set za rezbarenje početnički",
                            Price = 79.90m,
                            ProductCategoryId = 3,
                            ProductImageUrl = "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Početni set za keramiku: 2kg gline, alati za modeliranje i upute.",
                            IsDeleted = false,
                            Name = "Keramičarski starter kit",
                            Price = 165.00m,
                            ProductCategoryId = 3,
                            ProductImageUrl = "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=400",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zaštitna pregača od prave goveđe kože sa 4 džepa za alat.",
                            IsDeleted = false,
                            Name = "Radionička pregača kožna",
                            Price = 65.00m,
                            ProductCategoryId = 4,
                            ProductImageUrl = "https://images.unsplash.com/photo-1556909114-44e3e9699e2b?w=400",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Brzo-stezna stolarska stega sa čeljustima od 300mm, pritisak do 200kg.",
                            IsDeleted = false,
                            Name = "Stega stolarska 300mm",
                            Price = 28.75m,
                            ProductCategoryId = 4,
                            ProductImageUrl = "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mješoviti set brusnih papira: granulacija 80, 120, 180, 240 i 320.",
                            IsDeleted = false,
                            Name = "Brusni papir set 50 kom",
                            Price = 19.90m,
                            ProductCategoryId = 4,
                            ProductImageUrl = "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ručni Alati"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Premium Materijali"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Kompleti za Početnike"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Pribor za Radionicu"
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int?>("HoursSpent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moj prvi projekat sa kompletom za obradu kože. Napravio sam klasični muški novčanik sa 6 slotova za kartice.",
                            HobbyId = 2,
                            HoursSpent = 12,
                            ImageUrl = "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
                            IsDeleted = false,
                            ProductId = 10,
                            Title = "Ručno izrađeni novčanik od kože",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Komplet od tri kutlače različitih veličina, ručno izrezbarene od jednog komada hrastovine.",
                            HobbyId = 1,
                            HoursSpent = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
                            IsDeleted = false,
                            ProductId = 9,
                            Title = "Set drvenih kutlača",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Od hrastove daske sam napravila zidnu policu u rustikalnom stilu. Dimenzije su 120x25cm.",
                            HobbyId = 1,
                            HoursSpent = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400",
                            IsDeleted = false,
                            ProductId = 5,
                            Title = "Rustikalna polica za knjige",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegantna futrola za naočale od tamnosmeđe kože sa magnetnim zatvaračem.",
                            HobbyId = 2,
                            HoursSpent = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400",
                            IsDeleted = false,
                            ProductId = 10,
                            Title = "Kožna futrola za naočale",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dekorativna figurica sove visine 15cm, izrezbarena od bukovog drveta.",
                            HobbyId = 6,
                            HoursSpent = 20,
                            ImageUrl = "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400",
                            IsDeleted = false,
                            ProductId = 11,
                            Title = "Rezbarena figurica sove",
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ručno oblikovana keramička zdjela promjera 30cm. Glazirana u toplim zemljanim tonovima.",
                            HobbyId = 4,
                            HoursSpent = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=400",
                            IsDeleted = false,
                            ProductId = 12,
                            Title = "Keramička zdjela za voće",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.ProjectReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ProjectReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Prelijepo urađen novčanik! Šavovi su savršeni.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 1,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Odličan rad za prvi projekat. Koža je lijepo obrađena.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 1,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Kutlače su prelijepe! Prirodna forma drveta je očuvana.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 2,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Praktične i lijepe, idealan poklon za kuhinju.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 2,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Rustični stil je fantastičan! Hrast je prelijepo došao do izražaja.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 3,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Polica izgleda profesionalno. Svaka čast na vještini!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 3,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Elegantna futrola, magnetni zatvarač je odličan dodatak.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 4,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Kvalitetna izrada, koža je mekana i ugodna na dodir.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 4,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Rezbarenje je nevjerovatno! Svako pero je vidljivo.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 5,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Ova sova izgleda kao da će progovoriti! Talent!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 5,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Keramička zdjela je prelijepa! Boje su tople i privlačne.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 6,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Ručni rad se vidi u svakom detalju. Divno!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProjectId = 6,
                            Rating = 5,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Odličan čekić, savršena ravnoteža i čvrst zahvat. Preporučujem!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 1,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Kvalitetna hrastova daska, samo je pakovanje moglo biti bolje.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 5,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Savršen komplet za početnike, sve što treba na jednom mjestu.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 9,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Dlijeto drži oštricu jako dobro, zadovoljna sam kupovinom.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 3,
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Komplet za kožu ima sve potrebno. Napravio sam novčanik!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 10,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Brusni papir je ok za cijenu, ali se brže troši.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 15,
                            Rating = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Bosanski Kovači d.o.o.",
                            Website = "https://bosanskikovaci.ba"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Zanatlija Mostar",
                            Website = "https://zanatlija.ba"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Drvni Majstor Tuzla",
                            Website = "https://drvnimajstor.ba"
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted]= 0");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "Korisnik",
                            PasswordHash = "$2a$11$r2qfyc5ic4xn12pabxQnqutUdAnwvk.pZk9868MOTFC4Jo6dQOCPK",
                            PhoneNumber = "+38761000000",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amir@mail.com",
                            FirstName = "Amir",
                            IsDeleted = false,
                            LastName = "Hadžić",
                            PasswordHash = "$2a$11$8DGhfdncLbX2/fqYXGvIQ.8PpoMUXEltO5KPjLW7D1mYc6850OmDm",
                            PhoneNumber = "+38762111111",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
                            Role = 0,
                            Username = "amir.h"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lejla@mail.com",
                            FirstName = "Lejla",
                            IsDeleted = false,
                            LastName = "Begović",
                            PasswordHash = "$2a$11$8DGhfdncLbX2/fqYXGvIQ.8PpoMUXEltO5KPjLW7D1mYc6850OmDm",
                            PhoneNumber = "+38763222222",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
                            Role = 0,
                            Username = "lejla.b"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tarik@mail.com",
                            FirstName = "Tarik",
                            IsDeleted = false,
                            LastName = "Memić",
                            PasswordHash = "$2a$11$8DGhfdncLbX2/fqYXGvIQ.8PpoMUXEltO5KPjLW7D1mYc6850OmDm",
                            PhoneNumber = "+38761333333",
                            ProfileImageUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
                            Role = 0,
                            Username = "tarik.m"
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sarajevo",
                            Country = "Bosna i Hercegovina",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PostalCode = "71000",
                            Street = "Ferhadija 15",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            City = "Mostar",
                            Country = "Bosna i Hercegovina",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PostalCode = "88000",
                            Street = "Bulevar narodne revolucije 8",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            City = "Tuzla",
                            Country = "Bosna i Hercegovina",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PostalCode = "75000",
                            Street = "Turalibegova 22",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.UserHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId", "HobbyId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("UserHobbies");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 78.00m,
                            WishlistId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 65.00m,
                            WishlistId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 149.99m,
                            WishlistId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 38.50m,
                            WishlistId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 45.00m,
                            WishlistId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 189.00m,
                            WishlistId = 3
                        });
                });

            modelBuilder.Entity("Reignite.Core.Entities.Order", b =>
                {
                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Product", b =>
                {
                    b.HasOne("Reignite.Core.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Project", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Hobby", "Hobby")
                        .WithMany("Projects")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.Product", "Product")
                        .WithMany("Projects")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.ProjectReview", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Project", "Project")
                        .WithMany("Reviews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany("ProjectReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Review", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.UserAddress", b =>
                {
                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.UserHobby", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Hobby", "Hobby")
                        .WithMany("UserHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Wishlist", b =>
                {
                    b.HasOne("Reignite.Core.Entities.User", "User")
                        .WithOne("Wishlist")
                        .HasForeignKey("Reignite.Core.Entities.Wishlist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reignite.Core.Entities.WishlistItem", b =>
                {
                    b.HasOne("Reignite.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reignite.Core.Entities.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Hobby", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("UserHobbies");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Product", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Reignite.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Project", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Reignite.Core.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProjectReviews");

                    b.Navigation("Projects");

                    b.Navigation("Reviews");

                    b.Navigation("UserHobbies");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Reignite.Core.Entities.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
